<a href="https://colab.research.google.com/github/bipul-ranjan/newgithub/blob/master/NumPy_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

NumPy, an acronym for the term ‘Numerical Python’, is a library in Python which is used extensively for efficient mathematical computing.

This library allows users to store large amounts of data using less memory and perform extensive operations efficiently.

It provides optimised and simpler functionalities to perform aforementioned operations using homogenous, one-dimensional and multidimensional arrays

Now, before delving deep into the concept of NumPy arrays, it is important to note that Python lists can very well perform all the actions that NumPy arrays perform; it is simply the fact that NumPy arrays are faster and more convenient than lists when it comes to extensive computations, which make them extremely useful, especially when you are working with large amounts of data.

Some reasons for such difference in speed are:

NumPy is written in C, which is basically being executed behind the scenes


NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists



In [ ]:
#pip install numpy
import numpy as np

In [ ]:
import time

## Comparing time taken for computation
list_1 = [i for i in range(1000000)]
list_2 = [j**2 for j in range(1000000)]

t0 = time.time()
product_list = list(map(lambda x, y: x*y, list_1, list_2))
t1 = time.time()
list_time = t1 - t0
print (t1-t0)

# numpy array
array_1 = np.array(list_1)
array_2 = np.array(list_2)

t0 = time.time()
product_numpy = array_1 * array_2
t1 = time.time()
numpy_time = t1 - t0
print (t1-t0)

print("The ratio of time taken is {}".format(list_time//numpy_time))

0.2801337242126465
0.010195493698120117
The ratio of time taken is 27.0


You might hear of a 0-D (zero-dimensional) array referred to as a “scalar”

1-D (one-dimensional) array as a “vector”

2-D (two-dimensional) array as a “matrix”

N-D (N-dimensional, where “N” is typically an integer greater than 2) array as a “tensor”.

For clarity, it is best to avoid the mathematical terms when referring to an array because the mathematical objects with these names behave differently than arrays (e.g. “matrix” multiplication is fundamentally different from “array” multiplication), and there are other objects in the scientific Python ecosystem that have these names (e.g. the fundamental data structure of PyTorch is the “tensor”).

# Numpy vs List

In [ ]:
heights =  [74,75,72,73,72]

In [ ]:
np_heights = np.array(heights)
print(np_heights)

[74 75 72 73 72]


In [ ]:
np_heights * 2.54

array([187.96, 190.5 , 182.88, 185.42, 182.88])

# Array Creation

In [ ]:
a = np.array([2,3,4,5])
a

array([2, 3, 4, 5])

In [ ]:
a.ndim

1

In [ ]:
a.dtype

dtype('int32')

In [ ]:
b = np.array([1.2,3.5,5.3])
b.dtype

dtype('float64')

In [ ]:
b = np.array([[1,3,4,6],
            [2,4,5,8],
            [6,8,9,10]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(3, 4)

In [ ]:
c = np.array([[1,2],[3,4]],dtype = float)
c

array([[1., 2.],
       [3., 4.]])

In [ ]:
c.shape

(2, 2)

In [ ]:
a = np.ones((4,3,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
a.ndim

3

In [ ]:
a.shape

(4, 3, 4)

In [ ]:
b =  np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b[0:3,1:3]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
c =  np.arange(48).reshape(3,4,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [ ]:
c[1:2,1:3,0:3]

array([[36, 37, 38],
       [40, 41, 42]])

# Sorting

In [ ]:
arr = np.array([2,1,5,3,6,7,2,8])
sorted_arr = np.sort(arr)
sorted_arr[::-1]

array([8, 7, 6, 5, 3, 2, 2, 1])

# Aggregate Functions

In [ ]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b.sum()

66

In [ ]:
b.min()

0

In [ ]:
b.max()

11

In [ ]:
b.sum(axis=0)# sum of each columns

array([18, 22, 26])

In [ ]:
b.sum(axis=1)# sum of each rows

array([ 3, 12, 21, 30])

In [ ]:
# stacking
a1 = np.array([[1,1],
             [2,2]])

a2 = np.array([[3,3],
             [4,4]])

In [ ]:
#vstack
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
#hstack
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
np.unique(arr)

array([1, 2, 3, 5, 6, 7, 8])

In [ ]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [ ]:
np.add(a1,a2)

array([[4, 4],
       [6, 6]])

In [ ]:
np.subtract(a1,a2)
np.multiply(a1,a2)
np.divide(a1,a2)